logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.example: TRACE

spring:
  data:
    mongodb:
      host: 192.168.1.16
      port: 27017
      database: dustman


mybatis:
  configuration:
    map-underscore-to-camel-case: true
